// <auto-generated />
using System;
using Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(TokenForgeContext))]
    partial class TokenForgeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.LoginAttempt", b =>
                {
                    b.Property<Guid>("LoginAttemptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastAttemptAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAttempt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginAttemptID");

                    b.HasIndex("UserAttempt");

                    b.HasIndex("UserId", "LastAttemptAt");

                    b.ToTable("LoginAttempts");
                });

            modelBuilder.Entity("Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PermissionDescription")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PermissionId");

                    b.HasIndex("PermissionCode")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b109"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "auth.login",
                            PermissionDescription = "Authenticate and start a session.",
                            PermissionName = "Login"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b10a"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "auth.logout",
                            PermissionDescription = "Close the current authenticated session.",
                            PermissionName = "Logout"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b10c"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "tokens.refresh",
                            PermissionDescription = "Refresh an access token using a valid refresh token.",
                            PermissionName = "Refresh Token"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b101"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "tokens.revoke.current",
                            PermissionDescription = "Revoke refresh token of the current session.",
                            PermissionName = "Revoke Current Token"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b102"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "tokens.revoke.all",
                            PermissionDescription = "Revoke all refresh tokens for a target user.",
                            PermissionName = "Revoke All User Tokens"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b103"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "users.read",
                            PermissionDescription = "Read user information.",
                            PermissionName = "Read Users"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b104"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "users.write",
                            PermissionDescription = "Create or update users.",
                            PermissionName = "Write Users"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b10d"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "users.create",
                            PermissionDescription = "Create new users.",
                            PermissionName = "Create Users"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b10e"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "users.update.email",
                            PermissionDescription = "Update a user's email address.",
                            PermissionName = "Update User Email"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b10f"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "users.update.account",
                            PermissionDescription = "Update a user's account name.",
                            PermissionName = "Update User Account"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b110"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "users.update.password",
                            PermissionDescription = "Update a user's password.",
                            PermissionName = "Update User Password"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b111"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "users.disable",
                            PermissionDescription = "Disable user accounts.",
                            PermissionName = "Disable Users"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b112"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "users.read.roles",
                            PermissionDescription = "Read roles assigned to users.",
                            PermissionName = "Read User Roles"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b105"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "roles.read",
                            PermissionDescription = "Read role information.",
                            PermissionName = "Read Roles"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b106"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "roles.write",
                            PermissionDescription = "Create or update roles.",
                            PermissionName = "Write Roles"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b113"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "roles.update",
                            PermissionDescription = "Update role information.",
                            PermissionName = "Update Roles"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b114"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "roles.read.users",
                            PermissionDescription = "Read users assigned to roles.",
                            PermissionName = "Read Role Users"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b115"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "permissions.read",
                            PermissionDescription = "Read permission information.",
                            PermissionName = "Read Permissions"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b116"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "permissions.create",
                            PermissionDescription = "Create new permissions.",
                            PermissionName = "Create Permissions"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b117"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "permissions.update",
                            PermissionDescription = "Update existing permissions.",
                            PermissionName = "Update Permissions"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b118"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "permissions.activate",
                            PermissionDescription = "Reactivate permissions.",
                            PermissionName = "Activate Permissions"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b119"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "permissions.deactivate",
                            PermissionDescription = "Deactivate permissions.",
                            PermissionName = "Deactivate Permissions"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b11a"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "rolepermissions.assign",
                            PermissionDescription = "Assign permissions to roles.",
                            PermissionName = "Assign Role Permissions"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b11b"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "rolepermissions.revoke",
                            PermissionDescription = "Revoke permissions from roles.",
                            PermissionName = "Revoke Role Permissions"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b11c"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "rolepermissions.sync",
                            PermissionDescription = "Synchronize permissions assigned to a role.",
                            PermissionName = "Sync Role Permissions"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b11d"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "rolepermissions.read",
                            PermissionDescription = "Read role-permission assignments.",
                            PermissionName = "Read Role Permissions"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b107"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "userroles.assign",
                            PermissionDescription = "Assign roles to users.",
                            PermissionName = "Assign User Roles"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b108"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "userroles.revoke",
                            PermissionDescription = "Revoke role assignments from users.",
                            PermissionName = "Revoke User Roles"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b11e"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "userroles.read",
                            PermissionDescription = "Read user-role assignments.",
                            PermissionName = "Read User Roles"
                        });
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokensId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RefreshTokensId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("RolesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleDescription")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RolesId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RolesId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RoleDescription = "System administrator",
                            RoleName = "Admin"
                        },
                        new
                        {
                            RolesId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a002"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RoleDescription = "Team manager with operational permissions",
                            RoleName = "Manager"
                        },
                        new
                        {
                            RolesId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a003"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RoleDescription = "Basic user role",
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeactivatedReason")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RolePermissionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c010"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b109"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c011"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b10a"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c013"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b10c"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c001"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b101"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c002"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b102"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c003"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b103"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c004"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b104"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c014"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b10d"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c015"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b10e"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c016"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b10f"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c017"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b110"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c018"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b111"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c019"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b112"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c005"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b105"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c006"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b106"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c01a"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b113"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c01b"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b114"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c01c"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b115"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c01d"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b116"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c01e"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b117"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c01f"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b118"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c020"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b119"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c021"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b11a"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c022"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b11b"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c023"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b11c"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c024"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b11d"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c007"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b107"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c008"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b108"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c025"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b11e"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c026"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b109"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a002")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c027"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b10a"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a002")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c029"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b10c"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a002")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c009"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b101"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a002")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c00a"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b103"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a002")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c00b"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b104"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a002")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c02a"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b10d"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a002")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c02b"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b10e"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a002")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c02c"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b10f"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a002")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c02d"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b110"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a002")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c02e"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b111"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a002")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c02f"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b112"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a002")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c00c"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b105"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a002")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c030"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b113"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a002")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c031"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b114"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a002")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c00d"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b107"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a002")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c00e"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b108"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a002")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c032"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b11e"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a002")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c033"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b11d"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a002")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c00f"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b101"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a003")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c034"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b109"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a003")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c035"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b10a"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a003")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c037"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b10c"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a003")
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UsersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAccount")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UsersId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserAccount")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeactivatedReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Domain.Entities.LoginAttempt", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
