// <auto-generated />
using System;
using Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.DataAccess.Migrations
{
    [DbContext(typeof(TokenForgeContext))]
    [Migration("20260306013345_SeedPermissionsRolesAndBootstrapAdmin")]
    partial class SeedPermissionsRolesAndBootstrapAdmin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.LoginAttempt", b =>
                {
                    b.Property<Guid>("LoginAttemptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastAttemptAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAttempt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginAttemptID");

                    b.HasIndex("UserAttempt");

                    b.HasIndex("UserId");

                    b.ToTable("LoginAttempts");
                });

            modelBuilder.Entity("Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PermissionDescription")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PermissionId");

                    b.HasIndex("PermissionCode")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b101"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "tokens.revoke.current",
                            PermissionDescription = "Revoke refresh token of the current session.",
                            PermissionName = "Revoke Current Token"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b102"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "tokens.revoke.all",
                            PermissionDescription = "Revoke all refresh tokens for a target user.",
                            PermissionName = "Revoke All User Tokens"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b103"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "users.read",
                            PermissionDescription = "Read user information.",
                            PermissionName = "Read Users"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b104"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "users.write",
                            PermissionDescription = "Create or update users.",
                            PermissionName = "Write Users"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b105"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "roles.read",
                            PermissionDescription = "Read role information.",
                            PermissionName = "Read Roles"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b106"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "roles.write",
                            PermissionDescription = "Create or update roles.",
                            PermissionName = "Write Roles"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b107"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "userroles.assign",
                            PermissionDescription = "Assign roles to users.",
                            PermissionName = "Assign User Roles"
                        },
                        new
                        {
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b108"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionCode = "userroles.revoke",
                            PermissionDescription = "Revoke role assignments from users.",
                            PermissionName = "Revoke User Roles"
                        });
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokensId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RefreshTokensId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("RolesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleDescription")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RolesId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RolesId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RoleDescription = "System administrator",
                            RoleName = "Admin"
                        },
                        new
                        {
                            RolesId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a002"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RoleDescription = "Team manager with operational permissions",
                            RoleName = "Manager"
                        },
                        new
                        {
                            RolesId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a003"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            RoleDescription = "Basic user role",
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeactivatedReason")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RolePermissionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c001"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b101"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c002"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b102"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c003"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b103"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c004"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b104"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c005"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b105"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c006"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b106"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c007"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b107"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c008"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b108"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a001")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c009"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b101"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a002")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c00a"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b103"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a002")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c00b"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b104"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a002")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c00c"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b105"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a002")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c00d"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b107"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a002")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c00e"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b108"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a002")
                        },
                        new
                        {
                            RolePermissionId = new Guid("4fa8aab1-4ee8-4e54-b1f0-8af8f022c00f"),
                            AssignedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PermissionId = new Guid("7cc9d620-07c7-40d2-a5a7-95e0d1c0b101"),
                            RoleId = new Guid("4d2d7af9-2c7f-4f42-8a3d-7e7e26a6a003")
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UsersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAccount")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UsersId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeactivatedReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Domain.Entities.LoginAttempt", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
